version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: server
    restart: unless-stopped
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - APP_MODE=PRODUCTION
    depends_on:
      - db
      - redis
    ports:
      - "7000:7000"

  db:
    image: postgres:15
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  redis:
    build:
      context: ./redis
    hostname: redis
    ports:
      - 6379:6379

