version: "3.7"

services:

  db:
    image: postgres:15
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432

  redis:
    build:
      context: ./redis
      dockerfile: ./Dockerfile.redis
    restart: unless-stopped
    hostname: redis
    ports:
      - 6379:6379

